### ISSUE TITLE
Hi, task.Task struct has no field `HostPorts`, How can we fix this?

### ISSUE THREAD

**Issue by GaiheiluKamei** [buildorchestratoringo/code#1]
https://github.com/buildorchestratoringo/code/blob/beec5891718c42067231b59b5d12d20b9e09331a/ch9/worker/worker.go#L179

Hi, 
   I am studying your book, in chapter 9.4.2, at the last of function `updateTask()` has one problem:

1. The `task.Task` struct doesn't have a field called `HostPorts`, should it be `ExposedPorts`?
2. If it is `ExposedPorts`, its type is `nat.PortSet`, but the type of `resp.Container.NetworkSettings.NetworkSettingsBase.Ports` is `nat.PortMap`, how can we fix this? should we change all `nat.PortSet` to `nat.PortMap` or in opposite? @timboring 

```go
// task is running, update exposed ports
w.Db[id].HostPorts = resp.Container.NetworkSettings.NetworkSettingsBase.Ports
```

**Comment by GaiheiluKamei** [comment]
I solved this by doing so:

1. Add a `HostPorts` field in `task.Task` struct:

```go
// task/task.go
type Task struct {
    // ...
    HostPorts nat.PortMap
}
```

2. In the `manager/manager.go` file, update the function `func (m *Manager) updateTasks()`, add `mt.HostPorts = t.HostPorts`:

```go
// manager/manager.go
func (m *Manager) updateTasks() {
	for _, worker := range m.Workers {
		log.Printf("Checking worker %v for task updates", worker)
		url := fmt.Sprintf("http://%s/tasks", worker)
		resp, err := http.Get(url)
		if err != nil {
			log.Printf("Error connecting to worker %v: %v", worker, err)
		}
		d := json.NewDecoder(resp.Body)
		var tasks []*task.Task
		err = d.Decode(&tasks)
		if err != nil {
			log.Printf("Error decoding tasks: %s\n", err.Error())
		}

		for _, t := range tasks {
			id := t.ID
			log.Printf("Attempting to update task %v\n", id)

			mt, ok := m.TaskDb[id]
			if !ok {
				log.Printf("Task with ID %s not found\n", id)
				return
			}

			if mt.State != t.State {
				mt.State = t.State
			}

			mt.StartTime = t.StartTime
			mt.FinishTime = t.FinishTime
			mt.ContainerID = t.ContainerID
			mt.HostPorts = t.HostPorts // here need to update too
		}
	}
}
```

**Comment by wtran29** [comment]
Weird this change did not show up in the rest of the chapters... I ran into this also and was looking all over
